export const services = [
  {
    id: "classic-manicure",
    title: "Classic Manicure",
    description: "Basic nail care for your hands with regular polish",
    price: "$30",
    duration: "30 min",
    category: "manicure",
  },
  {
    id: "gel-manicure",
    title: "Gel Manicure",
    description: "Long-lasting gel polish for your hands",
    price: "$45",
    duration: "45 min",
    category: "manicure",
  },
  {
    id: "classic-pedicure",
    title: "Classic Pedicure",
    description: "Basic nail care for your feet with regular polish",
    price: "$40",
    duration: "45 min",
    category: "pedicure",
  },
  {
    id: "gel-pedicure",
    title: "Gel Pedicure",
    description: "Long-lasting gel polish for your feet",
    price: "$55",
    duration: "60 min",
    category: "pedicure",
  },
  {
    id: "nail-art",
    title: "Nail Art",
    description: "Custom designs on one or more nails",
    price: "$10+",
    duration: "15+ min",
    category: "art",
  },
  {
    id: "full-set-acrylics",
    title: "Full Set Acrylics",
    description: "Complete acrylic nail application",
    price: "$70",
    duration: "90 min",
    category: "extensions",
  },
]
